/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Scheduler;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author lavz24
 */
public class InPanel extends javax.swing.JFrame {

  /**
   * Creates new form Panel
   */
  public InPanel() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    Run = new javax.swing.JButton();
    inputQuantum = new javax.swing.JTextField();
    inputProcces = new javax.swing.JTextField();
    fileButton = new javax.swing.JButton();
    fileDirecction = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    errorLabel = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    inputTime = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel1.setText("Seconds per tick:");

    jLabel2.setText("File: ");

    jLabel3.setText("Ammount of processes:");

    Run.setText("Run");
    Run.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mousePressed(java.awt.event.MouseEvent evt) {
        RunMousePressed(evt);
      }
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        RunMouseClicked(evt);
      }
    });
    Run.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        RunActionPerformed(evt);
      }
    });

    inputQuantum.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        inputQuantumActionPerformed(evt);
      }
    });

    fileButton.setText("Buscar");
    fileButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        fileButtonMouseClicked(evt);
      }
    });

    jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18));
    jLabel4.setText("Linux  Scheduling Simulator");

    errorLabel.setForeground(new java.awt.Color(255, 0, 51));

    jLabel5.setText("Access time for Disk: ");

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
        .addContainerGap(143, Short.MAX_VALUE)
        .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 282, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .add(110, 110, 110))
      .add(layout.createSequentialGroup()
        .add(208, 208, 208)
        .add(Run, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 112, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(215, Short.MAX_VALUE))
      .add(layout.createSequentialGroup()
        .add(35, 35, 35)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(layout.createSequentialGroup()
            .add(jLabel2)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 52, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
              .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(errorLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 389, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(48, 48, 48))
              .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(fileDirecction, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(91, 91, 91))))
          .add(layout.createSequentialGroup()
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
              .add(jLabel1)
              .add(jLabel3)
              .add(jLabel5))
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 256, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
              .add(org.jdesktop.layout.GroupLayout.TRAILING, inputTime, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
              .add(org.jdesktop.layout.GroupLayout.TRAILING, inputProcces, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
              .add(org.jdesktop.layout.GroupLayout.TRAILING, inputQuantum, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
              .add(org.jdesktop.layout.GroupLayout.TRAILING, fileButton))
            .add(24, 24, 24))))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(errorLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .add(69, 69, 69)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel1)
          .add(inputQuantum, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .add(18, 18, 18)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel5)
          .add(inputTime, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .add(7, 7, 7)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(inputProcces, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .add(18, 18, 18)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(layout.createSequentialGroup()
            .add(fileDirecction, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(18, 18, 18)
            .add(fileButton)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 35, Short.MAX_VALUE)
            .add(Run, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
          .add(layout.createSequentialGroup()
            .add(jLabel2)
            .add(0, 154, Short.MAX_VALUE)))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void RunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_RunActionPerformed

  private void RunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RunMouseClicked
    // TODO add your handling code here:
    String [] arguments = new String[4];
    try{
    Integer.parseInt(inputQuantum.getText());
    Integer.parseInt(inputProcces.getText());
    Integer.parseInt(inputTime.getText());
    }
    catch(NumberFormatException e){
      errorLabel.setText("Quantum, Procces or Disk Time inserted is not  integer.");
      return;
    }
    
    if(fileDirecction.getText() == "" ){
       errorLabel.setText("Not file selected.");
      return;
    }
    
    if(Integer.parseInt(inputQuantum.getText())< 0 
            ||  Integer.parseInt(inputProcces.getText())<0
            ||  Integer.parseInt(inputTime.getText())<0 )
    {
      
      errorLabel.setText("Quantum, Procces or Disk Time inserted is not a positive integer.");
      return;
    
    }
    
    arguments[0] = inputQuantum.getText();
    arguments[1] = fileDirecction.getText();
    arguments[2] = inputProcces.getText();
    arguments[3] = inputTime.getText();
   // errorLabel
    this.dispose();
    Main.main(arguments);
       
  }//GEN-LAST:event_RunMouseClicked

  private void RunMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RunMousePressed
    // TODO add your handling code here:
  }//GEN-LAST:event_RunMousePressed

  private void fileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fileButtonMouseClicked
    // TODO add your handling code here:
    filePanel.main(this);
  }//GEN-LAST:event_fileButtonMouseClicked

  private void inputQuantumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputQuantumActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_inputQuantumActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /*
     * Set the Nimbus look and feel
     */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the
     * default look and feel. For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(InPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(InPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(InPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(InPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /*
     * Create and display the form
     */
    java.awt.EventQueue.invokeLater(new Runnable() {

      public void run() {
        new InPanel().setVisible(true);
      }
    });
    
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton Run;
  private javax.swing.JLabel errorLabel;
  private javax.swing.JButton fileButton;
  public javax.swing.JLabel fileDirecction;
  private javax.swing.JTextField inputProcces;
  private javax.swing.JTextField inputQuantum;
  private javax.swing.JTextField inputTime;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  // End of variables declaration//GEN-END:variables
}
